version = 2
final_space = true
console_title_template = '{{.Folder}}{{if .Root}} :: root{{end}}'

[[blocks]]
type = 'prompt'
alignment = 'left'

[[blocks.segments]]
type = 'status'
style = 'plain'
foreground_templates = ['{{ if .Error }}red{{ end }}']
template = ' {{ if .Error }}{{ else }}{{ end }} '
foreground = 'green'

[blocks.segments.properties]
always_enabled = true

[[blocks.segments]]
type = 'path'
style = 'diamond'
leading_diamond = ''
trailing_diamond = ''
template = '  {{ .Path }} '
background = 'lightGreen'
foreground = '#000000'

[blocks.segments.properties]
style = 'folder'

[[blocks.segments]]
type = 'sysinfo'
style = 'powerline'
powerline_symbol = ''
template = '  {{ round .PhysicalPercentUsed .Precision }}% '
background = '#607D8B'
foreground = '#ffffff'

[blocks.segments.properties]
precision = 2.0

[[blocks.segments]]
type = 'python'
style = 'powerline'
powerline_symbol = ''
template = ' {{ if .Venv }}({{ .Venv }}) {{ end }}'
background = 'blue'
foreground = '#FFFFFF'

[blocks.segments.properties]
display_mode = 'enviroment'
home_enabled = true

[[blocks.segments]]
type = 'python'
style = 'powerline'
powerline_symbol = ''
template = '  {{ .Full }} '
background = 'yellow'
foreground = '#000000'

[blocks.segments.properties]
display_mode = 'enviroment'
home_enabled = true

[[blocks.segments]]
type = 'git'
style = 'powerline'
powerline_symbol = ''
template = '{{if .UpstreamIcon }} {{ .UpstreamIcon }}{{ end }} {{ .HEAD }} {{ if .Working.Changed }}  {{ .Working.String }} {{ end }}'
background = '#FF9800'
foreground = '#000000'

[blocks.segments.properties]
fetch_stash_count = true
fetch_status = true
fetch_upstream_icon = true

[blocks.segments.properties.untracked_modes]
'/Users/user/Projects/oh-my-posh/' = 'no'
